### ISSUE TITLE
Connected Workspaces: Shared Resource Content Update

### ISSUE THREAD

**Issue by matthewjrob** [savvi-legal/feedback#160]

**Comment by danielandelin** [comment]
![image](https://user-images.githubusercontent.com/68620849/154571943-2becccbf-52bf-4116-8520-1890372f3eae.png)

**Comment by matthewjrob** [comment]
Recommending for the content update for shared resources: "(name of source account)"

**Comment by wmerfalen** [comment]
Hello, what page is this on? Also, how would I get to that page? Can we reproduce this on staging? If so, can you give me the steps to see this on staging?

**Comment by wmerfalen** [comment]
For the sake of documentation, here is how you get to that page.

1) Login to *STAGING* as daniel.andelin+qa@savvi.legal 
2) Go to this link https://staging.savvi.legal/c/296/home
3) Click `Send an NDA Assessment`

The issue lies in the drop down. Notice how it looks like this:
![Screen Shot 2022-02-22 at 4 42 36 PM](https://user-images.githubusercontent.com/2633195/155238495-a65e9527-f76d-4a78-9a7f-5165b3da4cbc.png)
 

The `0 from Master LLC` should just be `(Master LLC)`
