### ISSUE TITLE
Standing Form - Resource Creation - Merge

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#163]
Any way we can do a check on the two resources that get created and if they are the same it will only create one resource?

![image](https://user-images.githubusercontent.com/68620849/154779084-1259b97f-dc14-4a85-8020-c7c0569fd240.png)

**Comment by BrackCarmony** [comment]
Is this on a persistent form?  
If so the endpoint does allow the merging of two draft resources, 
Though in order to currently use that endpoint it is checking that the user is an admin on the account.

We could either setup a sister endpoint that allows draft resources to be merged so long as they are both on the same persistent form.

Pros:
- Could allow a user to combine the resources together in case there are multiple redundent questions up front, 

Cons: 
- More front end work needed, as well as not intuitive how to display as well as let them recreate a new draft resource in case they need to back out.

Or we could have it auto make that connection when the persistent form is submitted, it checks if it thinks the resources can be merge.

Pros: 
- We know they have finished the form and shouldn't need to split it back into two separate pieces, 
- The form filer doesn't need to think about if they should be combined.
Cons: 
- No way to consolidate the questions down
- Typos would not get consolidated

**Comment by danielandelin** [comment]
@BrackCarmony What is the status on this? It seems like this is combining resources even if they aren't the same name now on live.
