### ISSUE TITLE
Staging - Documents are generating on PandaDoc but not sending (High priority)

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#171]
You can use any document workflow but for simplicity -

Go to Onboard Employees

Add a new employee and select "Non-Compete Agreement"

Submit

Start Non-Compete Agreement

Submit (make sure `Send Pandadoc Documents on finalize(dev-only feature)` is checked, as well as that the document is sent automatically)

Document doesn't show up.

![image](https://user-images.githubusercontent.com/68620849/155815252-99dff22f-15b6-4df6-b2d9-9740d7796c37.png)

**Comment by SHRoberts91** [comment]
It looks like there's multiple issues that are most likely arising during the Finalize Task(transaction) and/or panda doc web hooks firing off when that document is generated.
A few things to take note of after briefly looking into it:
- The document is being created in panda doc
- The document is being saved in the `document_history` table.
- the `account_transaction_id` & `account_project_id` aren't being saved on the `document_history` item, which is why it's not showing up in the Task view after finalize.
- The Panda document status is staying in `document.draft`, the status should be `document.sent`
- No emails are being sent.

**Comment by SHRoberts91** [comment]
<img width="1678" alt="Screen Shot 2022-03-07 at 11 43 57 AM" src="https://user-images.githubusercontent.com/16089848/157097800-5fcde87f-cf65-4d3e-b8c8-5cdfb4141e00.png">

**Comment by SHRoberts91** [comment]
Important differences circled:
<img width="1469" alt="Screen Shot 2022-03-07 at 11 48 20 AM" src="https://user-images.githubusercontent.com/16089848/157098641-5b322988-5410-4c0f-a1ec-7246d1565baf.png">
