### ISSUE TITLE
Upgrade Plan is still showing when an account has been give access to a subscription through a portfolio

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#176]
![image](https://user-images.githubusercontent.com/68620849/156237919-6d77b0f4-72d4-4901-8afd-e1a54370dea2.png)

We need to make that upgrade plan go away for companies that already have a subscription through their portfolio (Partner Group)

**Comment by SHRoberts91** [comment]
Just need access to `db.partner.included_subscriptions`. Preferably through `GET /api/account/me`, but fine if we initially pass it through `GET api/account/partner`. Currently that property isn't getting passed through anywhere we're getting partner data, maybe just need to make it public.

**Comment by SHRoberts91** [comment]
@wmerfalen Looks like the `has_partner_subscriptions` value works sometimes, but not others. Steps to reproduce bug:
1. Make sure you're logged into `services@savvi.legal`.
2. Go to https://staging.savvi.legal/c/1865564677/home
3. View the `/api/account/me` payload
4. `has_partner_subscriptions` is set to true, even though that account is only connected to the `For-Profit Company Packages` Partner, which has no included subscriptions. (you can view this by filtering the `account_partner` table by the `account_id` of `1865564677`)

This isn't breaking anything on the front end since I haven't connected that yet, but we'll have to figure out that bug before I do connect it.

**Comment by wmerfalen** [comment]
@SHRoberts91 this has been fixed and pushed to staging and main
