### ISSUE TITLE
Currently Unable to add resources directly into admin portal

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#182]
I can't add resources into the admin portal data directly

**Comment by SHRoberts91** [comment]
I looked more into it and it looks like the resource is getting created, but for whatever reason it always gets saved with abn account_id of 33 instead of the account that is selected.

Steps to recreate:

1. go to staging.admin.savvi.legal
2. login
3. Pick a company on that top dropdown, or just use the default company.
4. click on the 'Individual' box to uncollapse that section
5. at the top of that section, add a name then click 'Add Resource'
