### ISSUE TITLE
Upgrading subscription - Client upgraded but it didn't prorate his subscription for him.

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#198]
![image](https://user-images.githubusercontent.com/68620849/158696411-a6b2a889-f495-4016-bfc1-57fc563258b4.png)

Also didn't remove the starter plan.

![image](https://user-images.githubusercontent.com/68620849/158696537-9238dc71-5405-4d07-9610-dfee0774a77a.png)

**Comment by SHRoberts91** [comment]
It looks like the prorating when upgrading from starter to advanced is working correctly in Staging and Demo, but I know there's certain differences in the way we handle the Stripe testing env vs the Stripe live env, just not sure of all those nuances. @BrackCarmony could you glance over the items in the stripe_bundle & stripe_product table and stripe itself to see if you notice anything off? Or if there's unique handling in the codebase around Stripe for production there's a good chance that was broken or just removed while reformatting, so that could be good to check as well.

**Comment by BrackCarmony** [comment]
@danielandelin do you know if this partial refund was something we did manually?
https://dashboard.stripe.com/payments/pi_3KUKbcE4vfjnPKYF0HZBkqYT

**Comment by SHRoberts91** [comment]
@BrackCarmony Yeah they went and manually refunded him after it happened

**Comment by SHRoberts91** [comment]
The action they did I believe was cancel and refund remaining subscription

**Comment by BrackCarmony** [comment]
- Assumption we are still using the bundle endpoint to create these subscriptions.
Looking at the DB and Code, it looks like the product_ids on the stripe_bundle table are incorrect.  They need to list all the product_ids that are covered by the current subscription.

IE Premium needs to list the product_ids of all 3 premium, advanced, and starter.

The product_ids field tells us which subscriptions this new bundle will be replacing.  This is complicated by the fact that there are other subscriptions that exist regardless of the level such as registered agent or state compliance, so we don't just get to say the newest subscription replaces all their current subscriptions. 

On the staging environment it is cascading as it should be.

**Comment by BrackCarmony** [comment]
It removed the correct subscription and issued a partial refund when I tested it on a test account on live after making those changes.  Seems to have resolved the issue, though there will still be issues if upgrading from a legacy subscription, (from 2+ years ago before we went with the starter, advanced, premium system)

**Comment by SHRoberts91** [comment]
Nice, then we'll close this for now and just keep an eye on it 👍
