### ISSUE TITLE
Annual Report Schedules - Admin Portal

### ISSUE THREAD

**Issue by danielandelin** [savvi-legal/feedback#220]
I can't get this page to work - Can't save new schedules or update schedules. Would love some more functionality around this. 

I want to be able to add Select the company, select the state, enter in the filing date and have it auto create that schedule.

https://admin.savvi.legal/#/ScheduleRule

**Comment by wmerfalen** [comment]
Will put this in our dev cycle as per your request on Slack

**Comment by wmerfalen** [comment]
The page that @danielandelin wants is actually here: https://staging.admin.savvi.legal/#/schedule (staging)

We need a few things:
1) Update the UI so that DA can add/update/create/delete entries in that table
2) Add/Update existing routes to accomodate the routes needed in step 1
3) Use the `calculateNextAnnualDate` function to allow DA to do step 4
4) DA wants to: add a new company, input state, and input filing date
5) The scheduled data should be calculated correctly by the function in step 3
